### PR TITLE
Add UBSan invoker test

### PR DESCRIPTION
**Pull request by Kojoley**
ref #29

### CODE REVIEW

**Comment by pdimov** [comment]
Interesting that it doesn't fail with g++. Perhaps they've fixed their sanitizer. :-)

**Comment by Kojoley** [comment]
> Interesting that it doesn't fail with g++

I have spotted this yesterday https://github.com/boostorg/function/pull/29#issuecomment-432048409

> Perhaps they've fixed their sanitizer. :-)

I did not try the latest GCC, maybe it is a regression, or new inspection.

**Comment by jeking3** [comment]
A very minor nit, perhaps, but placing the two UBSAN jobs together in `.travis.yml` would be nicer.

**Comment by jeking3** [comment]
Thanks.  Now what do folks want to do with this one? :)

**Comment by jeking3** [comment]
So does this expose a bug in gcc-8 ubsan, or is it catching something that it never caught before but should have?

**Comment by Kojoley** [comment]
It depends on if hidden visibility flag on classes contained in multiple LTO units is considered ODR violation.

**Comment by pdimov** [comment]
A similar test to the one in this PR is now part of the develop branch (https://github.com/boostorg/function/commit/17716b63f2a27d7b2bf0a170da31fa5079a495ec).

**Pull request closed without merging**
