### PR TITLE
Bunch of small tweaks

### PR DESCRIPTION
**Pull request by Kojoley**

### CODE REVIEW

**Comment by pdimov** [comment]
Interesting, your other PR is failing with an error somewhere inside Boost.Test (a reminder maybe that we need to switch to lightweight_test), while this one passes. I don't offhand see a reason for that.

**Comment by Kojoley** [comment]
I just factored out something from it before pushing to GH. I found one problem, but now I get infinity recursion in macros :disappointed:

**Comment by jeking3** [comment]
I rebased these in instead of squashing them since they all target different things.

**Comment by Kojoley** [comment]
It was not need rebase because it was already on-top of master HEAD so it could be simply fast-forward merged, but for some reason GitHub merge button is the way it is :-).

**Pull request merged**
