### PR TITLE
Add throw/catch test for bad_function_call

### PR DESCRIPTION
**Pull request by pdimov**
Curious to see the CI results on this one. Refs #24.

### CODE REVIEW

**Comment by pdimov** [comment]
Works perfectly. :-)

**Comment by apolukhin** [comment]
That's great news! Chances to break something with setting visibility to hidden seem to be quite low on modern compilers.

I'm interested to see the test results for Intel compiler and for GCC 4.4 or older.

**Comment by pdimov** [comment]
4.4 is included. Intel... don't exactly make it easy to use their compiler on Travis. :-)

**Comment by apolukhin** [comment]
That's interesting. Could you please also add a test:
```
// in shared library
std::exception get_ex() { static boost::bad_function_call ex; return ex; }

// in executable
assert(typeid(get_ex()) == typeid(boost::bad_function_call));
dynamic_cast<boost::bad_function_call&>(get_ex()); // should not throw
```

**Comment by pdimov** [comment]
@jeking3 Functions have always worked without `dllimport`, since before there even was `dllimport`. You do need `dllimport` for variables though.

@apolukhin You can try these yourself - just make another PR from this one. (It's on the branch `pr/shared-throw-test`.)

**Comment by jeking3** [comment]
@pdimov were you intending this to be merged, or were you just using boostorg CI?

**Comment by pdimov** [comment]
It wouldn't hurt to test whether `bad_function_call` can be caught, so we might just as well merge it, even if it didn't expose a problem today.

**Comment by jeking3** [comment]
Sounds good.  Can't complain about additional testing!  Always a good thing.

**Pull request merged**
