### PR TITLE
replace members of std::allocate which are deprecated in c++17 by the…

### PR DESCRIPTION
**Pull request by DanielaE**
…irs cousins from std::allocator_traits.

### CODE REVIEW

**Comment by DanielaE** [comment]
It looks like Travis isn't configured correctly for Linux clang.

**Comment by eldiener** [comment]
We do not want to be checking for MSVC in particular. Instead what we want is to be using the config macro BOOST_NO_CXX11_ALLOCATOR to determine what the code should be. So please remove all the:

#if !((__cplusplus > 201700) || (defined(_MSVC_LANG) && (_MSVC_LANG > 201700)))

and substitute in its place:

#if defined(BOOST_NO_CXX11_ALLOCATOR)

then test.

**Comment by pdimov** [comment]
I updated `.travis.yml`. g++ 7 in C++17 mode fails one test though, due to a compiler bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81311. I reported that 5 months ago but nothing seems to have happened on that front, so perhaps we need to `#ifdef` that out for g++ 7 in C++17 mode?

**Comment by pdimov** [comment]
Yes, we do need to `#ifdef` it out, and we did, in https://github.com/boostorg/function/commit/eba48932f0904e49c773cf2b8981c4df26100636. :-)

**Comment by DanielaE** [comment]
@eldiener 
> and substitute in its place:
> #if defined(BOOST_NO_CXX11_ALLOCATOR)

Great - done. That was my preferred solution in the first place. But then I chose to follow Boost.Config's precedent on this particular topic ...

**Comment by eldiener** [comment]
Thanks for implementing this change.

**Pull request merged**
